language: node_js
node_js:
  - "stable"
before_install:
- openssl aes-256-cbc -K $encrypted_8b34ab5bd7eb_key -iv $encrypted_8b34ab5bd7eb_iv
  -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git --version
install:
  - npm install --no-optional
script:
  - npm run build
after_success:
  - chmod a+x deploy-to-gh-pages.sh
  - npm run deploy
branches:
  only:
    - master
